version: '2'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod
  
  nlp:
    build: ./nlp
    container_name: nlp
    environment:
      - DB_HOST=mongodb
      - SERVER_HOST=nlp
      - SERVER_PORT=8081
    volumes:
      - ./nlp:/nlp
    ports:
      - 8081:8081
    links:
      - mongodb
    depends_on:
      - mongodb
    command: ./start.sh
  
  server:
    build: ./server
    container_name: server
    environment:
      - DB_HOST=mongodb
      - SERVER_PORT=8080
      - NLP_HOST=nlp
      - NLP_PORT=8081
    volumes:
      - ./server:/server
    ports:
      - 8080:8080
    links:
      - mongodb
      - nlp
    depends_on:
      - mongodb
      - nlp
    command: npm start
