version: '2'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod

  server:
    build: ./server
    container_name: server
    environment:
      - SERVER_PORT=8080
      - DB_HOST=mongodb
    volumes:
      - ./scripts:/scripts
      - ./server:/server
    ports:
      - 8080:8080
    links:
      - mongodb
    depends_on:
      - mongodb
    command: npm start
