env: dev
server:
  port: 8080
database:
  host: localhost
  port: 27017
  db: kibo
  collections:
    disorders: disorders
    phenotypes: phenotypes
    disorders_classification: disorders_classification
    phenotypes_classification: phenotypes_classification
sparql:
  hpo: http://172.17.0.2:9999/blazegraph/namespace/hpo/sparql
  ordo: http://172.17.0.2:9999/blazegraph/namespace/ordo/sparql
nlp:
  host: localhost
  port: 5000
scoring:
  threshold: 90
  results_size: 5
  frequency_factors:
    - label: Obligate (100%)
      value: 1.5
    - label: Very frequent (99-80%)
      value: 1.4
    - label: Frequent (79-30%)
      value: 1.3
    - label: Occasional (29-5%)
      value: 1.2
    - label: Very rare (<4-1%)
      value: 1

